apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2021-06-16T13:14:05Z"
    labels:
      app: db
    name: db
    namespace: demo-ns
    resourceVersion: "27126"
    uid: 62606e9d-e57d-45d2-a253-4eaa1766ebfb
  spec:
    clusterIP: 10.102.213.106
    clusterIPs:
    - 10.102.213.106
    ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      app: db
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2021-06-16T13:13:53Z"
    labels:
      app: wordpress
    name: wordpress
    namespace: demo-ns
    resourceVersion: "27114"
    uid: 1c486f06-c9cf-4133-9f9c-3506d4de6b6d
  spec:
    clusterIP: 10.109.20.250
    clusterIPs:
    - 10.109.20.250
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 32313
      port: 8080
      protocol: TCP
      targetPort: 80
    selector:
      app: wordpress
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
