apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-06-16T10:08:34Z","labels":{"run":"db"},"name":"db","namespace":"demo-ns","resourceVersion":"18993","uid":"8d38e513-3d2e-4be5-a9ad-f7c9c79b06ad"},"spec":{"clusterIP":"10.98.210.31","clusterIPs":["10.98.210.31"],"externalTrafficPolicy":"Cluster","ports":[{"nodePort":32635,"port":3306,"protocol":"TCP","targetPort":3306}],"selector":{"run":"db"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2021-06-16T10:19:11Z"
    labels:
      run: db
    name: db
    namespace: demo-ns
    resourceVersion: "19481"
    uid: 91a27454-56b5-4a1e-b1a4-8892196605b3
  spec:
    clusterIP: 10.98.210.31
    clusterIPs:
    - 10.98.210.31
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 32635
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      run: db
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-06-16T09:51:29Z","labels":{"run":"wordpress"},"name":"wordpress","namespace":"demo-ns","resourceVersion":"18234","uid":"f1778f46-f7d1-4a95-bc34-42dfa8e01cc0"},"spec":{"clusterIP":"10.103.251.145","clusterIPs":["10.103.251.145"],"externalTrafficPolicy":"Cluster","ports":[{"nodePort":31284,"port":8080,"protocol":"TCP","targetPort":80}],"selector":{"run":"wordpress"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
    creationTimestamp: "2021-06-16T10:19:11Z"
    labels:
      run: wordpress
    name: wordpress
    namespace: demo-ns
    resourceVersion: "19493"
    uid: c38d7880-485e-4fb4-a332-e9cda91fdec5
  spec:
    clusterIP: 10.103.251.145
    clusterIPs:
    - 10.103.251.145
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 31284
      port: 8080
      protocol: TCP
      targetPort: 80
    selector:
      run: wordpress
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
